# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a860fca30a3a2690e80f504630b44243b979ad75c2fa0c083c8aa20f1f0ab3ab76f1490ca0c060b6c8aed54553968818eb5de4d7fcd291afc7b9e3780d7c984a

test:
  secret_key_base: a2fdab1b15ba6c25f838db9011979625acfd9a6462fb3b28d3176463aea3e5961d3e3f3cab800e0a6389ca1e76b184bef6e935dc2837ed89950f7094f244ebb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
